<a href="https://colab.research.google.com/github/Laticzka/colabb/blob/main/numpy_wstep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(help(np))


Tworzenie tablicy typu ndarray
Tablica 1D

In [ ]:
tab1D = np.array([4, 9, 1, 67, 23])
print(tab1D)

[ 4  9  1 67 23]


Parametry tablicy ndarray

In [ ]:
print(tab1D.ndim)
print(tab1D.size)
print(tab1D.shape)

1
5
(5,)


Tworzenie tablicy typu ndarray Tablica 2D

In [ ]:
tab2D = np.array([[3, 8], [-1, 12]])

Parametry tablicy ndarray

In [ ]:
print(tab2D.ndim)
print(tab2D.size)
print(tab2D.shape)

2
4
(2, 2)


Zmiana kształtu tablicy

In [ ]:
tab2D = np.array([[1, 2], [3, 4], [5, 6]])
print(tab2D.shape)
print(tab2D)

tab2D = tab2D.reshape((2, 3))
print(tab2D)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


Tablica samych zer

In [ ]:
tab0 = np.zeros(shape = (3, 5))
print(tab0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Tablica samych jedynek

In [ ]:
tab1 = np.ones(shape =(3, 5))
print(tab1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Tablica samych piątek

In [ ]:
tab5 = np.full(shape = (3, 5), fill_value = 5.0)
print(tab5)

Tablica z przedziału

In [ ]:
tab_przedzial = np.arange(0, 10.01, 0.01)
print(tab_przedzial)

[ 0.    0.01  0.02 ...  9.98  9.99 10.  ]


In [ ]:
tab_liczba_el = np.linspace(0, 10.0, 50)
print(tab_liczba_el)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


Losowanie - sposób 1 (moduł random)

In [ ]:
import random
lista = []
for i in range(100):
  lista.append(random.randint(1, 1000))
print(lista)

[335, 759, 455, 171, 754, 621, 36, 997, 586, 966, 466, 978, 686, 770, 555, 466, 839, 189, 172, 992, 170, 111, 478, 808, 200, 7, 313, 502, 964, 380, 168, 697, 652, 986, 686, 101, 445, 808, 197, 613, 353, 593, 197, 233, 671, 282, 715, 996, 326, 642, 526, 972, 301, 557, 941, 195, 60, 46, 835, 260, 98, 756, 587, 531, 24, 984, 481, 68, 911, 638, 459, 649, 237, 204, 210, 155, 359, 201, 833, 398, 321, 966, 373, 220, 764, 35, 537, 596, 715, 271, 767, 503, 693, 425, 212, 670, 546, 927, 775, 868]


Losowanie pierwszych 10-ciu liczb z przedziału od 1 do 100,
kolejnych 10-ciu z przedziału od 101 do 200 itd.

In [ ]:
lista2 = []
for i in range(10):
  for j in range(10):
    lista2.append(random.randint(100 * i + 1, 100 * i + 100))
print(lista2)

[79, 49, 47, 33, 18, 48, 44, 88, 98, 35, 153, 130, 158, 175, 178, 182, 178, 196, 160, 165, 201, 282, 266, 298, 297, 258, 286, 260, 219, 228, 361, 367, 344, 400, 332, 325, 394, 367, 327, 351, 415, 481, 466, 499, 404, 418, 447, 432, 414, 426, 595, 548, 600, 558, 557, 526, 543, 535, 590, 570, 654, 637, 685, 649, 673, 655, 652, 662, 661, 663, 790, 725, 798, 705, 717, 798, 792, 744, 780, 792, 831, 857, 889, 821, 837, 824, 843, 895, 811, 879, 973, 964, 986, 935, 971, 940, 919, 908, 902, 911]


Wszystkie komponenty modułu numpy

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

Dostęp do poszczególnych elementów

In [ ]:
tab_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(tab_2d[0][1])
print(tab_2d[[1, 2]])

2
[[3 4]
 [5 6]]


In [ ]:
tab1 = np.ones(shape = (3, 5), dtype = 'int')
print(tab1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
