<a href="https://colab.research.google.com/github/Laticzka/colabb/blob/main/numpy_wstep_cz_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
dir(np)

In [ ]:
help(np)

In [ ]:
lista = [3, -1, 8, 9, 2, 7, 11]
tab1D_1 = np.array(lista)
tab1D_1

array([ 3, -1,  8,  9,  2,  7, 11])

In [ ]:
print(2 * lista)

[3, -1, 8, 9, 2, 7, 11, 3, -1, 8, 9, 2, 7, 11]


In [ ]:
print(2 * tab1D_1)

[ 6 -2 16 18  4 14 22]


Wyświetlamy parametry tablicy - liczba wymiarów (czyli 2d, 3d itd.), kształt, rozmiar(liczba elementów), typ

In [ ]:
print(tab1D_1.ndim) #nie trzeba używać printów
print(tab1D_1.shape)
print(tab1D_1.size)
print(tab1D_1.dtype)
type(tab1D_1)

1
(7,)
7
int64
int64


In [ ]:
tab1D_2 = np.array([3, -1, 8, 9, 2, 7, 11], type = "float64")

TWORZENIE TABLICY 2D

In [ ]:
tab2D = np.array([[1, 4, 7], [2, 8, 1]])
tab2D

array([[1, 4, 7],
       [2, 8, 1]])

In [ ]:
lista3D = []
for i in range(3):
  for w in range(2):
    for j in range():
tab3D = np.array([])